### ISSUE TITLE
existdb-core-2.2.pom not working

### ISSUE THREAD

**Issue by brettenbacher** [eXist-db/mvn-repo#7]
The pom has a 2.1 version and seems to be a renamed copy of existdb-core-2.1.pom.

**Comment by adamretter** [comment]
Thanks for reporting I just corrected this.

To update please make sure to remove your cached local maven repository copy first e.g.

```bash
rm -rf ~/.m2/repository/org/exist-db/existdb-core
```

and then run `mvn` with the `-U` argument
