### ISSUE TITLE
Update to v3.0

### ISSUE THREAD

**Issue by joewiz** [eXist-db/mvn-repo#8]
The exist-db.org homepage says this repo contains 3.0RC1. I assume this repo needs to be updated for the final 3.0 release too.

**Comment by dizzzz** [comment]
Yes :)

**Comment by adamretter** [comment]
I am trying to do that now, but the Git tag is wrong so it cannot be done until we fix that

**Comment by adamretter** [comment]
So I couldn't do this from the Git tag regrettably, so I used commit 9911af8.
Whilst this is very confusing, it is the best we can achieve until we release 3.1.
